export const SEPARATED_GRAPHS = 'SEPARATED_GRAPHS'
export const RADAR_GRAPH = 'RADAR_GRAPH'
export const BAR_GRAPH = 'BAR_GRAPH'
export const TABLE = 'TABLE'
export const FINNISH = 'fi'
export const ENGLISH = 'en'
